openapi: 3.0.0
info:
  title: Your API
  version: 1.0.0
paths:
  /add_employee:
    post:
      summary: Create a new resource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parameter1:
                  type: string
                parameter2:
                  type: integer
                # Add more properties as needed
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
