# Generated by Django 5.0.1 on 2024-01-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('EmoployeeName', models.CharField(max_length=500)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFieldName', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='EmployeeID',
            new_name='DepartmentID',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='Department',
            new_name='DepartmentName',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='DateOfJoining',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='EmoployeeName',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='PhotoFieldName',
        ),
    ]
