# Generated by Django 5.0.1 on 2024-01-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapiapp", "0003_rename_emoployeename_employee_employeename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Other",
            fields=[
                ("EmpID", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
