# Generated by Django 5.0.1 on 2024-01-18 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapiapp", "0004_other"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Other",
        ),
    ]
